//! Verify byte-for-byte signing parity with `pm-sdk-go`.
//!
//! Reads `pm-sdk-go/pkg/signer/testdata/golden.json` and checks every fixture against
//! `predict-rs-clob-client::signer`. If any digest, struct hash, or signature drifts, Phase 2 will
//! produce orders the backend rejects — so this is the canary test.

use predict_rs_clob_client::signer::{
    OrderForSigning, PMCup26Signer, clob_auth_digest, clob_auth_domain_separator,
    clob_auth_struct_hash, order_digest, order_domain_separator, order_struct_hash,
};
use predict_rs_clob_client::types::{Address, B256, ScopeId, U256};

use serde::Deserialize;

/// Local copy of `pm-sdk-go/pkg/signer/testdata/golden.json`. The fixture is regenerated by
/// running pm-sdk-go's signer test suite; if pm-sdk-go's testdata changes, sync this file too.
const GOLDEN_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/golden.json"
);

#[derive(Debug, Deserialize)]
struct Golden {
    private_key: String,
    clob_auth: Vec<ClobAuthVec>,
    orders: Vec<OrderVec>,
    domain_separators: DomainSeparators,
}

#[derive(Debug, Deserialize)]
struct ClobAuthVec {
    name: String,
    chain_id: u64,
    address: String,
    timestamp: String,
    nonce: u64,
    scope_id_hex: String,
    domain_separator: String,
    struct_hash: String,
    digest: String,
    signature: String,
    recovered_address: String,
}

#[derive(Debug, Deserialize)]
struct OrderVec {
    name: String,
    chain_id: u64,
    exchange_address: String,
    salt: String,
    maker: String,
    signer: String,
    taker: String,
    token_id: String,
    maker_amount: String,
    taker_amount: String,
    expiration: u64,
    nonce: u64,
    fee_rate_bps: u64,
    side: u8,
    signature_type: u8,
    scope_id_hex: String,
    domain_separator: String,
    struct_hash: String,
    digest: String,
    signature: String,
    #[allow(dead_code)] // present in fixture; verified implicitly through signature match
    recovered_address: String,
}

#[derive(Debug, Deserialize)]
struct DomainSeparators {
    clob_auth_chain_1: String,
    clob_auth_chain_137: String,
    ctf_exchange_chain_1: String,
    ctf_exchange_chain_137: String,
}

fn load_golden() -> Golden {
    let text = std::fs::read_to_string(GOLDEN_PATH).expect("read golden.json");
    serde_json::from_str(&text).expect("parse golden.json")
}

fn parse_hex32(s: &str) -> [u8; 32] {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    let bytes = hex::decode(stripped).expect("hex decode");
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

fn b256_from_hex(s: &str) -> B256 {
    B256::from(parse_hex32(s))
}

fn addr_from_hex(s: &str) -> Address {
    s.parse::<Address>().expect("address parse")
}

fn u256_from_str(s: &str) -> U256 {
    s.parse::<U256>().expect("u256 parse")
}

fn private_key_bytes(g: &Golden) -> [u8; 32] {
    let stripped = g.private_key.strip_prefix("0x").unwrap_or(&g.private_key);
    let bytes = hex::decode(stripped).expect("private key hex");
    assert_eq!(bytes.len(), 32, "private key must be 32 bytes");
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

fn sig_bytes_from_hex(s: &str) -> [u8; 65] {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    let bytes = hex::decode(stripped).expect("sig hex");
    assert_eq!(bytes.len(), 65, "signature must be 65 bytes");
    let mut out = [0u8; 65];
    out.copy_from_slice(&bytes);
    out
}

#[test]
fn precomputed_domain_separators_match() {
    let g = load_golden();
    assert_eq!(
        clob_auth_domain_separator(1),
        b256_from_hex(&g.domain_separators.clob_auth_chain_1),
        "ClobAuth chain=1 domain separator drift"
    );
    assert_eq!(
        clob_auth_domain_separator(137),
        b256_from_hex(&g.domain_separators.clob_auth_chain_137),
        "ClobAuth chain=137 domain separator drift"
    );
    // Order domain uses exchange address from the golden orders fixture (all use same 0x4bFb...).
    let exchange = addr_from_hex(&g.orders[0].exchange_address);
    assert_eq!(
        order_domain_separator(1, exchange),
        b256_from_hex(&g.domain_separators.ctf_exchange_chain_1),
        "Order chain=1 domain separator drift"
    );
    assert_eq!(
        order_domain_separator(137, exchange),
        b256_from_hex(&g.domain_separators.ctf_exchange_chain_137),
        "Order chain=137 domain separator drift"
    );
}

#[test]
fn clob_auth_fixtures_match() {
    let g = load_golden();
    let pk = private_key_bytes(&g);

    for v in &g.clob_auth {
        let address = addr_from_hex(&v.address);
        let scope_id = ScopeId::from_hex(&v.scope_id_hex).expect("scope_id parse");

        // Domain separator
        let want_ds = b256_from_hex(&v.domain_separator);
        let got_ds = clob_auth_domain_separator(v.chain_id);
        assert_eq!(got_ds, want_ds, "case {}: domain separator drift", v.name);

        // Struct hash
        let want_sh = b256_from_hex(&v.struct_hash);
        let got_sh = clob_auth_struct_hash(address, &v.timestamp, v.nonce, scope_id);
        assert_eq!(got_sh, want_sh, "case {}: struct hash drift", v.name);

        // Full EIP-712 digest
        let want_digest = b256_from_hex(&v.digest);
        let got_digest = clob_auth_digest(address, &v.timestamp, v.nonce, scope_id, v.chain_id);
        assert_eq!(got_digest, want_digest, "case {}: digest drift", v.name);

        // Signature (RFC 6979 deterministic — should match go-ethereum exactly).
        let signer = PMCup26Signer::from_private_key(&pk, v.chain_id)
            .expect("signer construct")
            .with_scope_id(scope_id);
        // The fixture's `address` should match the signer's recovered address.
        assert_eq!(
            signer.address(),
            addr_from_hex(&v.recovered_address),
            "case {}: signer.address mismatch",
            v.name
        );
        let got_sig = signer.sign_clob_auth(&v.timestamp, v.nonce).expect("sign");
        assert_eq!(
            hex::encode(got_sig),
            hex::encode(sig_bytes_from_hex(&v.signature)),
            "case {}: signature drift",
            v.name
        );
    }
}

#[test]
fn order_fixtures_match() {
    let g = load_golden();
    let pk = private_key_bytes(&g);

    for v in &g.orders {
        let scope_id = ScopeId::from_hex(&v.scope_id_hex).expect("scope_id parse");
        let exchange = addr_from_hex(&v.exchange_address);

        let order = OrderForSigning {
            salt: u256_from_str(&v.salt),
            maker: addr_from_hex(&v.maker),
            signer: addr_from_hex(&v.signer),
            taker: addr_from_hex(&v.taker),
            token_id: u256_from_str(&v.token_id),
            maker_amount: u256_from_str(&v.maker_amount),
            taker_amount: u256_from_str(&v.taker_amount),
            expiration: v.expiration,
            nonce: v.nonce,
            fee_rate_bps: v.fee_rate_bps,
            side: v.side,
            signature_type: v.signature_type,
            scope_id,
        };

        // Domain separator
        let want_ds = b256_from_hex(&v.domain_separator);
        let got_ds = order_domain_separator(v.chain_id, exchange);
        assert_eq!(got_ds, want_ds, "case {}: domain separator drift", v.name);

        // Struct hash
        let want_sh = b256_from_hex(&v.struct_hash);
        let got_sh = order_struct_hash(&order);
        assert_eq!(got_sh, want_sh, "case {}: struct hash drift", v.name);

        // Digest
        let want_digest = b256_from_hex(&v.digest);
        let got_digest = order_digest(&order, exchange, v.chain_id);
        assert_eq!(got_digest, want_digest, "case {}: digest drift", v.name);

        // Signature
        let signer = PMCup26Signer::from_private_key(&pk, v.chain_id)
            .expect("signer construct")
            .with_scope_id(scope_id)
            .with_exchange(exchange);
        let got_sig = signer.sign_order(&order).expect("sign order");
        assert_eq!(
            hex::encode(got_sig),
            hex::encode(sig_bytes_from_hex(&v.signature)),
            "case {}: signature drift",
            v.name
        );
    }
}
